mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
  type-aliases-package: com.evan.server.bean
#config your SQL connection
spring:
  datasource:
    password: gan945815822.
    url: jdbc:mysql://localhost:3306/evan_server?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource