spring:
  profiles:
    active: dev
    include: mybatis-plus-config,log
  devtools:
    add-properties: false

---
#开发环境配置

server:
  port: 8081
spring:
  profiles: dev
swagger:
  isSwaggerEnable: true
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "
---
#测试环境配置
spring:
  profiles: stg

server:
  port: 8082

---
#生产环境配置
spring:
  profiles: pro

server:
  port: 8083
swagger:
  isSwaggerEnable: false